### ISSUE TITLE
New feature ideas

### ISSUE THREAD

**Issue by bramborman** [pcolby/nfc-quick-settings#42]
Hi, so I was thinking about my usage of this app and how it can be improved, and have a few ideas of what could be added:
- Launcher Activity with Getting Started guide - a simple video or steps to start using this app and also how to set up the advanced mode.
- Advanced mode without computer. Some apps are able to invoke adb commands from themselves - without a computer (for example Automate from LlamaLabs), and thinking about it, for as long as there's debugging over network enabled on the phone, if the app acts as the adb, it should just work over localhost.
- Customizations for various Android flavors. For instance, Samsung have its own built-in NFC toggle so for their users, it might make sense to recommend the native solution. Also, some manufacturers use different icons in the Quick Settings area, so using some more natively looking might make the app blend into the UI better. I worry it's not possible to do this on the resource level using qualifiers, such as `res/drawable/icon.xml` and `res/drawable/icon-xiaomi.xml`, unfortunately, so this would have to be done in the app code.
- Options to automatically turn NFC off in advanced mode. I, personally, use the toggle to enable NFC before payment and turn it off afterwards. It would be much more comfortable if I could set it to turn off automatically after, eg 3 minutes. This brings me to another feature that would play nice with this...
- Popup on click. On my Pixel phone, when I click the Bluetooth toggle, it opens a popup that allows me to turn Bluetooth on/off, but also a quick access to connect to paired devices. Similar effect could probably be achieved with "display on top of other apps" permission and an activity with a toggle and configuration of the time when to turn NFC back off automatically or other stuff.

Sorry for such a huge dump of features @pcolby. This is not a feature request, per se, but rather a dump of my ideas for such an app to get them out of my head 😅 I'd be glad to implement them myself when I find some time, I've already been thinking about implementation details of some, but would like to know your thoughts on them of course 😊

**Comment by pcolby** [comment]
Thanks @bramborman, there's some excellent ideas there, that are well worth exploring! 😄

Based on some of the recent discussions that have been happening in the Issues section, I've decided to enable GitHub's [Discussions](https://github.com/pcolby/nfc-quick-settings/discussions) feature for this repo.  I would be great if you create a separate post for each idea in the [Ideas](https://github.com/pcolby/nfc-quick-settings/discussions/categories/ideas) section, so we can easily discuss each one there? I'd be happy to do it myself, but it seems nicer that you get the credit for creating them 😉 But if you prefer me to do it, just let me know 😊

Thanks!

**Comment by bramborman** [comment]
I created discussions for each of the ideas, so closing this 😊

I'd love to implement them, but cannot promise I'll have the time soon :/
