### ISSUE TITLE
Door access

### ISSUE THREAD

**Issue by pergolafabio** [pcolby/nfc-quick-settings#52]
Hey, I found your app by this thread!!

https://support.google.com/pixelphone/thread/223215355/quickly-switch-off-nfc-or-make-device-unlock-truly-required?hl=en

I'm the same exact situation, I also have an NFC sticker behind my phone, it indeed only works when NFC is really off, seems indeed the antenna somehow stays active, if you enable the option to use NFC only when unlocked... That's too bad indeed...

Maybe you already have a solution for it besides turning  ff NFC completely with your app?

**Comment by pcolby** [comment]
Hi @pergolafabio,

> Maybe you already have a solution for it besides turning ff NFC completely with your app?

Nope, I have not found any other solution. Although I can set NFC to require unlock to work, the NFC radio is still active so it can 'detect' an NFC touch and prompt me to unlock. I can imagine this behaviour is desirable for some people / use cases, but as you know, it's a real pain if you have other devices that get confused by this radio's presence.

Anyway, the best option (for me, at least) remains to be this project 😊

Cheesrs.

**Comment by pergolafabio** [comment]
Indeed!! Going to test the adb command later, makes it indeed even easier!!

What phone do you have? I have pixel 8 now , with NFC gen2 tag behind... Cloned my fuel card on it, also use it for door access...

It's strange, I tested it also with OnePlus 7 phone, NFC enabled, and it was working with that one...

**Comment by pergolafabio** [comment]
It's still a strange behavior, normally if you approach an NFC reader with 2 tags, it should just pickup the first one...  

With android as a tag, it doesn't pickup any tag... If a NFC sticker is next to it...(Far enough from the NFC antenna)

Something is messing it up, maybe the wireless charging

**Comment by pcolby** [comment]
I'm closing this issue now, since it's not really something NFC Quick Settings can help with. But feel free to open a [discussion](https://github.com/pcolby/nfc-quick-settings/discussions) if you'd like to continue to discuss the idea/s 😊 Thanks!
